### ISSUE TITLE
object has no attribute 'strip'

### ISSUE THREAD

**Issue by francicco** [uym2/Triplet_rooting#14]
Hi,

I wanted to test the tool, but I'm getting this error executing the test data:

`tripVote_complete_trees.py -i incomplete.trees -o completed.trees`

```
Running TripletVoting version 1.1
tripVote_complete_trees was called as follow: ./tripVote_complete_trees.py -i incomplete.trees -o completed.trees
Traceback (most recent call last):
  File "/mnt/storage/scratch/tk19812/software/tripVote/./tripVote_complete_trees.py", line 66, in <module>
    main()    
  File "/mnt/storage/scratch/tk19812/software/tripVote/./tripVote_complete_trees.py", line 30, in main
    placement_set = args.placement.strip().split()
AttributeError: 'NoneType' object has no attribute 'strip'
```

Cheers
F

**Comment by uym2** [comment]
Hello Francicco,

Thank you for your interest in the tool and for pointing out this error. This is a *silly* mistake in our code in argument parsing; it occurs when we tried to add a new optional argument. We have fixed the problem in version 1.2; please just upgrade to the new version using ```pip install --upgrade TripletVoting```. Before rerunning, please check that you have obtained version 1.2 by ```tripVote_complete_trees.py -v```. 

Should you still see a problem, please let us know.

Thanks,
Uyen

**Comment by francicco** [comment]
Great! It works.
I'm gonna test it immediately with my data
Cheers
F

**Comment by francicco** [comment]
Would it be possible to implement a small change?
To return leaves original names instead of numbers?
Cheers
F

**Comment by uym2** [comment]
I believe the tool always returns leaves original names, although our test cases only have names as numbers. Have you tried with your actual data and not see it returns the original names?

**Comment by francicco** [comment]
Yes! It's perfect.
I have another question. How suitable would to use these completed gene trees to study introgression based on gene tree topology, like the one used in this [paper](https://linkinghub.elsevier.com/retrieve/pii/S0960982221014962)?

Cheers
F
